FROM maven:3.8.6-jdk-8-slim AS builder

WORKDIR /build

COPY . .

RUN mvn clean package -DskipTests -pl tduck-api -am

FROM amazoncorretto:8-alpine3.19-jre

RUN apk add --no-cache ttf-dejavu fontconfig tzdata

ENV TZ=Asia/Shanghai

WORKDIR /application

COPY --from=builder /build/tduck-api/target/tduck-api.jar application.jar

EXPOSE 8999

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Duser.language=zh -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom -jar application.jar --server.port=${PORT:-8999}"]
